### ISSUE TITLE
Error importing dateFormatter (corner case?)

### ISSUE THREAD

**Issue by Shauny-Boi** [corrieriluca/JSON-Messenger-Parser#8]
This might just be due to my specific configuration, I'm pretty inexperienced with Python.

I got the following error when trying to run the script:

`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from dateFormatter import dateFormat, frenchDateFormat
ModuleNotFoundError: No module named 'dateFormatter'`

I was able to fix it by renaming DateFormatter.py to dateFormatter.py in the git installation directory.

It could be my version of Python has a setting to care about case sensitivity or something?

I'm using "Python 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] on linux" via the WSL console, running Ubuntu 20.04

Once I got that sorted it worked very well - thank you very much!

**Comment by corrieriluca** [comment]
Hi, it seems very weird since it worked at the time I made the tool in 2019.

But indeed, I algo get this error, it may be something related to the Python version (I just tested with Python 3.9.2 on macOS and I got the error).

Thank you for your report, I'm gonna update the tool!
